### ISSUE TITLE
Peer proxyquire-universal@1.0.7 wants proxyquireify@>= 1 < 3

### ISSUE THREAD

**Issue by ch1bo** [bendrucker/proxyquire-universal#14] opened 2015-08-05 11:38 UTC
Hey, just encountered an invalid peer depencency when installing all three modules like in the README:
```
npm install --save-dev proxyquire-universal proxyquire proxyquireify
```
Obviously its because the latest version of `proxyquireify` is now `3.0`.

**Comment by bendrucker** [comment] 2015-08-05 16:25
Dupe of #12, #13

**Closed by bendrucker** 2015-08-05 16:25 UTC
